### ISSUE TITLE
Notification when a server is online or offline?

### ISSUE THREAD

**Issue by DSpectrumNGKK** [eclair4151/MinecraftServerStatusWidget#11]
Hi, i don't know if this is the right place to post ideas and if so then i apologise, but i have been using your app for a while and i've been wondering if it is possible if you could add a notification function when a server is back online or it's gone offline? It would be very useful. Please and thank you.

**Comment by eclair4151** [comment]
its a good idea but would require a cloud server to handle checking of servers and sending push notifications which I don't really have the time or funds to implement for this free app with less than 500 downloads. An alternative would be to run background task to check locally on the phone and send a notification but background tasks can only run every x hours so notifications would be super delayed
