### ISSUE TITLE
Lan server always offline

### ISSUE THREAD

**Issue by daafies** [eclair4151/MinecraftServerStatusWidget#12]
I have 2 servers on LAN and they always appear offline. What am i doing wrong

**Comment by eclair4151** [comment]
LAN Servers don't work for this app unfortunately. It must an internet connected server 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eclair4151** [comment]
With the most recent version of the app the will be on the store soon (1.1.0) local lan servers should now work

**Comment by daafies** [comment]
Cool! Thx

On May 12, 2020, at 08:08, Tomer Shemesh <notifications@github.com> wrote:

﻿

With the most recent version of the app the will be on the store soon (1.1.0) local lan servers should now work
