### ISSUE TITLE
'.dev' domain suffix never shows up as online

### ISSUE THREAD

**Issue by zcoop98** [eclair4151/MinecraftServerStatusWidget#13]
When using a domain ending in `.dev`, the server isn't recognized and permanently reads as offline.

I did some digging, and it appears the [underlying API](https://api.mcsrvstat.us/) currently breaks with `.dev` domains as well, which would explain this behavior. I'm not sure there's anything to be done here until the API addresses it.

**Comment by eclair4151** [comment]
Ah yea that’s odd. Not much I can do about it, but I will email the owner and ask if he is aware. Thanks for letting me know!

**Comment by eclair4151** [comment]
Do you mind letting me know what domain you are trying with?

**Comment by zcoop98** [comment]
Sweet! I went ahead and emailed about it as well using the email at the bottom of the API page.

Yeah! I was trying to use the app with a personal server I just put up a month ago, [zleo.dev](zleo.dev)

**Comment by zcoop98** [comment]
Welp, update; I totally jumped the gun here. This is related to an issue with my server, some kind of IPv6 routing issue, nothing to do with domain suffixes. Thanks for the response anyways!
