### ISSUE TITLE
Showing nick issue

### ISSUE THREAD

**Issue by Mimc14** [eclair4151/MinecraftServerStatusWidget#14]
![FFA57A48-C43A-42E9-B8FE-3EC21051F62D](https://user-images.githubusercontent.com/22458806/70848737-34db8f80-1e76-11ea-8ab6-91cb49b8ccc6.jpeg)

**Comment by eclair4151** [comment]
Hmm can you go into your settings app and go to 
General > Accessibility > Larger text and send a screen shot of what you have set?

**Comment by Mimc14** [comment]
![7A07F550-A1D7-4E1C-B8DD-4B1EAB33E30B](https://user-images.githubusercontent.com/22458806/70849375-b71b8200-1e7d-11ea-9df3-7c3dadb70fb3.png)

**Comment by eclair4151** [comment]
should be fixed with #21
