### ISSUE TITLE
Widget not compatible with iOS 13 Dark Mode

### ISSUE THREAD

**Issue by Wellonamed** [eclair4151/MinecraftServerStatusWidget#15]
The widget keeps using the light theme when the new iOS 13 Dark Mode is active. As a result, the widget looks out of place when used in tandem with other widgets that are optimized for Dark Mode.

![image](https://user-images.githubusercontent.com/19522020/81505773-bae1f200-92bf-11ea-9934-d7921a6d194a.jpeg)

**Comment by eclair4151** [comment]
I have updated the app and submitted a new version to the appstore. It should be on the store in about 2 days after apple reviews it.

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-05-12 at 10 08 12](https://user-images.githubusercontent.com/3183738/81703254-54cdaa00-943a-11ea-9e5b-36dfc27b3408.png)
