### ISSUE TITLE
hello im the guy from the appstore review

### ISSUE THREAD

**Issue by StinkyTACO** [eclair4151/MinecraftServerStatusWidget#16]
in response to what is no longer working its all of them even new ones, I add aren't working they load forever or just show up as offline.

**Comment by eclair4151** [comment]
Could you confirm what device you are using and if you are on WiFi? If so could you try on data? The app connects directly over the Minecraft port so if you have a firewall on your network it may not work.

Thanks
Tomer
________________________________

**Comment by StinkyTACO** [comment]
on data, it works, and now switching back to wifi it also works again. weird It hadn't worked for over a month but switching wifi off seemed to bring it back, thanks!
