### ISSUE TITLE
Server Status just with mobile data 

### ISSUE THREAD

**Issue by funbear** [eclair4151/MinecraftServerStatusWidget#17]
Server Stats, Players etc. just refresh with mobile data and not with WiFi. 
![EAC2BDB9-357D-44DD-90F8-E96E2A92490A](https://user-images.githubusercontent.com/48595218/84579280-d4012580-adcc-11ea-91a0-7c58d94e92a3.jpeg)

**Comment by eclair4151** [comment]
Hmm yea i've heard of this a few times. can you let me know, what wifi is this on? your home wifi or corporate? This connects over the minecraft port so im wondering if its being blocked by the router

**Comment by funbear** [comment]
It’s on my home WiFi. Hope this helps. Just ask if you have more questions.

**Comment by eclair4151** [comment]
Huh, ok so
1) what router do you have?
2) i assume Minecraft works on your home wifi?

**Comment by funbear** [comment]
I have a router from Telekom (I live in Germany near of Hannover.) minecraft works on my wifi and I can join multiplayer servers. The sim cart in the router is from o2.

**Comment by eclair4151** [comment]
fixed with d9d6367c09ed9b7aabb4b7315f8446a0e0cd0d7a
Should be on the store in the next few days

**Comment by eclair4151** [comment]
The app has been approved and is now on the store. Can you confirm if it fixes the issue?
