### ISSUE TITLE
Certain Server Issues

### ISSUE THREAD

**Issue by AceCaptainRex** [eclair4151/MinecraftServerStatusWidget#18]
It seems as if some larger servers, such as MunchyMC, Hypixel, and InvadedLands had not been working. I made a review on the App Store, in which I detailed this, and InvadedLands appeared to be fixed. (Yay! :D) However, even after this hotfix, it appears that Hypixel and MunchyMC are still not working. All information that I put in about those two servers are correct. I'm not sure why this would be happening :/

Thanks,
Ace

**Comment by eclair4151** [comment]
I have found the issue. They are using a slightly different version of the minecraft API, and returning a string as the description instead as a dictionary like the newer ones. I will update the parser to handle that and we should be good

**Comment by eclair4151** [comment]
fixed in 38e4c0f242a34843b24101baccc3b45ed7378122

**Comment by eclair4151** [comment]
The app is now live on the store. Can you check the update and confirm everything now works as expected?

**Comment by AceCaptainRex** [comment]
@eclair4151 - Yep, everything is working great! I really appreciate your quick and really awesome response! Will be updating my review to 5 stars. :D
