### ISSUE TITLE
IOS 14 widget style 

### ISSUE THREAD

**Issue by GidationBoy** [eclair4151/MinecraftServerStatusWidget#20]
It would be great if you guys can add the iOS 14 widget.

**Comment by eclair4151** [comment]
This is currently in progress. Expect an update within 1 month

**Comment by GidationBoy** [comment]
> This is currently in progress. Expect an update within 1 month

Thanks man, this feature will be awesome!

**Comment by GidationBoy** [comment]
@eclair4151 Could you also make it so that transparent icons are completely transparent in your next update? 
![50048A28-1AA2-4C31-A2FD-8507FAAC34F9](https://user-images.githubusercontent.com/71721387/105745852-b8d2c880-5f0c-11eb-83d2-ba1e32683902.jpeg)

**Comment by eclair4151** [comment]
If you would like to be a beta tester on test flight please email your apple id (tomerjshemesh@gmail.com) and I will add you once an initial build is ready for testing.

**Comment by GidationBoy** [comment]
> If you would like to be a beta tester on test flight please email your apple id ([tomerjshemesh@gmail.com](mailto:tomerjshemesh@gmail.com)) and I will add you once an initial build is ready for testing.

Yeah sure, does it have to be my Apple ID or can I use gmail?

**Comment by eclair4151** [comment]
We can try gmail that should be fine.

**Comment by GidationBoy** [comment]
Ok well use this email: gidation@gmail.com

**Comment by eclair4151** [comment]
Done with #21
