### ISSUE TITLE
Some labels are not bolded

### ISSUE THREAD

**Issue by schayes04** [eclair4151/MinecraftServerStatusWidget#4]
"Status" and "Motd" are not bolded on the one online server I have. They are bolded on the offline/unknown servers and the rest of the labels are still bolded

**Comment by eclair4151** [comment]
unable to reproduce

**Comment by schayes04** [comment]
I think it might be related to when the tableview cells get reused

https://imgur.com/a/H58Geqj

**Comment by eclair4151** [comment]
fixed in 05066c762399758fb76d79728fd26a9e4702df91
